#!/bin/bash
# configure.sh - Configure profile from template

PROFILES_DIR="$HOME/profiles"

configure_profile() {
    local profile="$1"
    local template_dir="$SCRIPT_DIR/profiles/free/$profile"
    local target_dir="$PROFILES_DIR/$profile"
    
    if [ ! -d "$template_dir" ]; then
        echo -e "${RED}✗ Profile template not found: $profile${NC}"
        exit 1
    fi
    
    echo "Configuring profile: $profile"
    
    # Create profile directory
    mkdir -p "$target_dir"
    mkdir -p "$target_dir/memories"
    mkdir -p "$target_dir/skills"
    
    # Copy SOUL.md if exists
    if [ -f "$template_dir/SOUL.md" ]; then
        cp "$template_dir/SOUL.md" "$target_dir/SOUL.md"
        echo -e "${GREEN}✓ SOUL.md copied${NC}"
    fi
    
    # Create default config.yaml if profile.yaml exists
    if [ -f "$template_dir/profile.yaml" ]; then
        # Create a basic config.yaml from profile.yaml
        cat > "$target_dir/config.yaml" << EOF
# Generated by agent-bootstrap
# Profile: $profile
# See profile.yaml for skill definitions
EOF
        echo -e "${GREEN}✓ config.yaml created${NC}"
    fi
    
    # Create empty MEMORY.md
    if [ ! -f "$target_dir/memories/MEMORY.md" ]; then
        touch "$target_dir/memories/MEMORY.md"
        echo -e "${GREEN}✓ MEMORY.md initialized${NC}"
    fi
    
    echo -e "${GREEN}✓ Profile configured at: $target_dir${NC}"
}
